version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-browsers

    steps:
      - checkout
      - run:
          ./gradlew build
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
      - store_test_results:
          path: ~/junit

      - store_artifacts:
          path: ~/junit

      - store_artifacts:
          path: apigee-publish-plugin/libs/apigee-publish-plugin.jar

  sonar-static-analysis:
    docker:
      - image: circleci/openjdk:11-jdk-browsers

    steps:
      - checkout
      - run:
          name: sonarqube static analysis
          command: ./gradlew sonarqube -Dsonar.login=$SONAR_TOKEN -Dsonar.branch.name=$CIRCLE_BRANCH

  publish-to-gradle-plugins:
    docker:
      - image: circleci/openjdk:11-jdk-browsers

    steps:
      - checkout
      - run:
          name: publish plugin
          command: ./gradlew publishPlugins -Pgradle.publish.key=$PUBLISH_KEY -Pgradle.publish.secret=$PUBLISH_SECRET

workflows:
  default:
    jobs:
      - build
      - sonar-static-analysis
      - publish-to-gradle-plugins-approval:
          requires:
            - build
            - sonar-static-analysis
          type: approval
          filters:
            branches:
              only: ['master']
      - publish-to-gradle-plugins:
          requires:
            - publish-to-gradle-plugins-approval
          filters:
            branches:
              only: ['master']
